[package]
name = "cotton-essentials"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
getset = "0.1.2"
log = "0.4.16"
colored = "2.0.0"
fern = "0.6.0"
chrono = "0.4.19"