[package]
name = "cotton-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
essentials = { path = "../essentials", package = "cotton-essentials" }
anyhow = "1.0.56"
byteorder = "1.4.3"